// Auto-generated by ESBMC 8.3.0
// This file provides concrete implementations of __VERIFIER_nondet_* functions

#include <math.h>

void __VERIFIER_assume(int cond) { (void)cond; }

char __VERIFIER_nondet_char(void) {
  static int i = 0;
  static const char v[] = { 0, 0, 0 };
  return v[i++];
}

int __VERIFIER_nondet_int(void) {
  static int i = 0;
  static const int v[] = { 0 };
  return v[i++];
}

void* __VERIFIER_nondet_pointer(void) {
  static int i = 0;
  static const void* v[] = { 0, 0, 0, 0, 0 };
  return v[i++];
}

unsigned char __VERIFIER_nondet_uchar(void) {
  static int i = 0;
  static const unsigned char v[] = { 0, 0 };
  return v[i++];
}

